Ajouter plusieurs positions à un numéro
etalab/editeur-bal pull request #293
Opened 2021-02-04 15:50 UTC by GllmR

Il est maintenant possible d'ajouter plusieurs positions, de type différent ou non, à un numéro.

Fix #287 

![Capture d’écran 2021-02-04 à 16 44 09](https://user-images.githubusercontent.com/56537238/106917408-85f8b380-6708-11eb-84a8-831afff8a814.png)

2021-02-08 10:09 UTC, cedric-famibelle-pronzola commented on components/bal/voie-editor.js
> +            'Déplacer les marqueurs sur la carte pour modifier les positions' :
Un toponyme peut-il avoir plus d'une position ?

2021-02-08 10:15 UTC, tmerlier commented on components/bal/position-editor.js
>    }).isRequired,
Non `PropTypes.shape` est utilisé pour les objects.

2021-02-08 10:17 UTC, cedric-famibelle-pronzola commented on components/bal/position-editor.js
>    }).isRequired,
c'est un array d'objets non ?

2021-02-08 10:50 UTC, GllmR commented on components/bal/numero-editor.js
> +    if (markers[0] && markers[0].latitude && markers[0].longitude && voie.trace) {
Il est possible que `markers[0]` n'ai qu'une propriété, cf ligne 147 `enableMarkers([{type: 'entrée'}])`

2021-02-08 10:55 UTC, GllmR commented on components/bal/voie-editor.js
> +    } else if (isToponyme || (isToponyme && initialValue && initialValue.positions.length === 0)) {
Non, parce qu'il est possible qu'il y est une `initalValue` sans `positions`

2021-02-08 15:21 UTC, cedric-famibelle-pronzola approved these changes

2021-02-10 10:06 UTC, tmerlier requested changes

2021-02-11 09:29 UTC, GllmR commented on contexts/markers.js
> +  const disableMarkers = useCallback(() => {
L'enlever va créer une boucle avec le `useEffect` qui suit.

2021-02-11 09:33 UTC, GllmR commented on contexts/markers.js
> +  const enableMarkers = useCallback(defaultMarkers => {
Lorsque je l'enlève, j'obtiens une erreur à la création d'une position.

2021-02-12 09:57 UTC, tmerlier approved these changes

2021-02-24 13:33 UTC, merged