Corrige l'édition groupée qui ajoute des toponymes non-sélectionnés
etalab/editeur-bal pull request #343
Opened 2021-05-20 16:21 UTC by GllmR

fix #340

2021-05-20 17:10 UTC, tmerlier commented on components/grouped-actions.js
> +      r.toponyme = selectedToponymeId || r.toponyme
De cette façon il n'est plus possible de dissocier les numéros d'un toponyme.

2021-05-25 11:48 UTC, cedric-famibelle-pronzola commented on components/grouped-actions.js
> +  const getDefaultPositionType = (hasMultiposition, selectedNumerosUniqType) => {
Si la méthode est à l'intérieur du composant, les arguments ne sont pas nécessaires.
Il faudrait pour le coup la placer après la ligne qui y fait appelle (L39).

2021-05-25 12:18 UTC, tmerlier requested changes

2021-05-25 12:18 UTC, tmerlier commented on components/grouped-actions.js
> +  const getDefaultPositionType = () => {
Si les arguments ne sont pas passé alors cette fonction doit être appelée dans une `useCallback` et les `states` doivent indiqué dans les hooks.

2021-05-25 14:17 UTC, tmerlier requested changes
Quand aucun des numéros sélectionnés n'a de toponymes, alors le champ "toponyme" doit afficher `'- Choisir un toponyme -`

2021-05-25 14:17 UTC, tmerlier commented on components/grouped-actions.js
> +  }, [isShown, getDefaultToponyme])
Ne peut pas fonctionner en l'état. Ce `useEffect` peut être supprimé car son comportement est remplacé par le `getDefaultToponyme`.

2021-05-26 07:43 UTC, tmerlier approved these changes

2021-05-26 07:45 UTC, merged