Ajout d'une alerte si la commune a déjà publiée un Base Adresse Locale
etalab/editeur-bal pull request #349
Opened 2021-06-03 14:50 UTC by GllmR

### ⚠️ Cette Pull Request a besoin de la Pull Request [#282](https://github.com/etalab/api-bal/pull/282) de l'api-bal ⚠️

Lorsque l'utilisateur crée une Base Adresse Locale, une boite de dialogue l'avertira si une Base Adresse Locale de la commune sélectionnée a déjà été publiée.
Si l'adresse électronique fournie par l'utilisateur correspond, il lui sera proposé de reprendre son travail sur cette Base Adresse Locale.

![image](https://user-images.githubusercontent.com/56537238/120664010-dbf92000-c48a-11eb-857a-03edbc895dcb.png)

![image](https://user-images.githubusercontent.com/56537238/120664081-eca99600-c48a-11eb-9163-85eb893def3d.png)

2021-06-07 10:32 UTC, tmerlier requested changes

2021-06-07 10:32 UTC, tmerlier commented on pages/new/create-form.js
> +  }, [commune, email])
Ce `useEffect` pourrait appeler inutilement plusieurs fois `checkIfPublished`, à chaque nouveau caractère entré par l'utilisateur dans `email` par exemple.

`isBalAlreadyPublished` doit être appelé au moment de la soumission du formulaire. On pourrait procéder comme ça:
1. Appel de `onSubmit`
2. Chargement
3. Vérification de la publication de la BAL
4. Si BAL déjà publié on affiche la popup sinon on continue normalement
5. L'utilisateur fait le choix de continuer la création, reprendre une BAL en cours ou annuler.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/create-form.js
> +  const [alreadyPublishedBAL, setAlreadyPublishedBAL] = useState()
Doit être initialisé à `null`

2021-06-07 10:32 UTC, tmerlier commented on pages/new/upload-form.js
> +  const [codeCommune, setCodeCommune] = useState()
Doit être initialisé à `null`

2021-06-07 10:32 UTC, tmerlier commented on pages/new/upload-form.js
> +  const [alreadyPublishedBAL, setAlreadyPublishedBAL] = useState()
Doit être initialisé à `null`

2021-06-07 10:32 UTC, tmerlier commented on pages/new/upload-form.js
> +    setCodeCommune(validateResponse?.rows[0].parsedValues.cle_interop.slice(0, 5))
Cette ligne est assez cryptique.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/upload-form.js
> +      setCodeCommune(validateResponse?.rows[0].parsedValues.cle_interop.slice(0, 5))
Pourquoi vérifier `file` et refaire appel à `validate` ici alors que cette vérification a déjà été faite dans `onDrop` ?

2021-06-07 10:32 UTC, tmerlier commented on pages/new/create-form.js
> +    if (commune) {
Pourquoi vérifier commune ?

2021-06-07 10:32 UTC, tmerlier commented on pages/new/upload-form.js
> +  }, [codeCommune, email])
Même problème que pour `create-form`, ce `useEffect` pourrait appeler inutilement plusieurs fois `checkIfPublished`, à chaque nouveau caractère entré par l'utilisateur dans email par exemple.

`isBalAlreadyPublished` doit être appelé au moment de la soumission du formulaire.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/alert-published-bal.js
> +  isShown: PropTypes.bool,
Cette n'est pas nécessaire, c'est le composant parent qui décide si `AlertPublishedBAL` doit être `render`.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/alert-published-bal.js
> +    if (alreadyPublishedBAL) {
`alreadyPublishedBAL` ne peut pas être `null`. C'est le composant parent qui décide de `render` `AlertPublishedBAL` justement si `alreadyPublishedBAL` existe ou non.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/alert-published-bal.js
> +      if (alreadyPublishedBAL.communes.length > 0) {
`alreadyPublishedBAL.communes` ne peut pas être vide sinon `AlertPublishedBAL` n'a pas d'intérêt à être `render`.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/alert-published-bal.js
> +  const onBalSelect = useCallback(bal => {
`useCallback` n'a pas d'intérêt ici.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/alert-published-bal.js
> +      createNewBal()
Ce n'est pas à ce composant de gérer la création de la BAL. C'est l'action d'annuler ou fermer la fenêtre qui pour appeler la création de BAL. Mais dans ce cas la pops a utilisée est `onClose` ou `onCancel`.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/alert-published-bal.js
> +  const [paragraph, setParagraph] = useState()
Il n'est pas nécessaire que ces variables soit des `states`.

2021-06-07 10:32 UTC, tmerlier commented on pages/new/alert-published-bal.js
> +  const [commune, setCommune] = useState()
Doit être initialisé à `null`.

2021-06-07 10:32 UTC, cedric-famibelle-pronzola commented on pages/new/alert-published-bal.js
> +          <Paragraph>Je veux <Link onClick={createNewBal} ><u>créer une nouvelle Base Adresse Locale</u><br /></Link> pour la commune de <b>{commune?.nom}</b></Paragraph>
En passant la souris sur le lien, le curseur est en `text` plutôt qu'en `pointer`

2021-06-07 10:32 UTC, cedric-famibelle-pronzola commented on pages/new/alert-published-bal.js
> +    if (alreadyPublishedBAL) {
Pourquoi cette condition ?

2021-06-07 10:32 UTC, cedric-famibelle-pronzola commented on pages/new/alert-published-bal.js
> +    }
Pourquoi faire appel à cette méthode ?

2021-06-08 15:25 UTC, tmerlier requested changes
Si l'API renvoi une liste de BAL alors l'application devrait aussi pouvoir proposer cette liste. Ça serait un bon raccourci au bouton "Récupérer mes BAL par courriel".

2021-06-08 15:25 UTC, tmerlier commented on pages/new/create-form.js
> +    const isPublished = await isBalAlreadyPublished(commune, email.toLowerCase())
Le traitement `email.toLowerCase()` n'est pas appliqué lors de lors soumission il serait donc préférable de ne pas le faire ici non plus.

Sinon une autre solution serait de l'appliquer dès le champ texte.

2021-06-08 15:25 UTC, tmerlier commented on pages/new/create-form.js
>            isShown={isShown}
`isShown={Boolean(alreadyPublishedBAL)}`

2021-06-08 15:25 UTC, tmerlier commented on pages/new/create-form.js
>    const [isShown, setIsShown] = useState(false)
L'affichage de l'alerte dépend de l'existence de `alreadyPublishedBAL`. Si celle-ci s'affiche les seules options de l'utilisateur seront de continuer la création ou de choisir une des BAL proposées donc il sortira de la page dans tous les cas et l'alerte ne pourra pas être réaffichée.

2021-06-08 15:25 UTC, tmerlier commented on pages/new/create-form.js
>        {alreadyPublishedBAL && (
Soit on utilise`isShown` soit cette condition mais les deux ne sont pas nécessaires.

2021-06-09 08:03 UTC, GllmR commented on pages/new/create-form.js
>    const [isShown, setIsShown] = useState(false)
C'est pour cette raison que j'ai conservé le `isShown` .

2021-06-16 17:14 UTC, cedric-famibelle-pronzola requested changes

2021-06-16 17:14 UTC, cedric-famibelle-pronzola commented on pages/new/upload-form.js
> +        })
`.then` n'est pas nécessaire.
Le résultat de la promesse peut être récupéré en stockant `Promise.all` dans une constante.

2021-06-21 14:21 UTC, cedric-famibelle-pronzola reviewed
Lors de l'affichage de la liste des BAL, un message indique 'Pas d’administrateur
pour les BAL de démonstration'.
Il faudrait adapter le composant pour que le texte soit différent

2021-06-22 08:18 UTC, cedric-famibelle-pronzola requested changes
Lors de l'affichage de la liste des BAL, le message sous le statut ne correspond pas au contexte.

![bal](https://user-images.githubusercontent.com/45098730/122888154-dd0ec600-d341-11eb-92ea-72741f78591a.png)

Il faudrait peut-être "fermer" les BAL quand il y a plus de 2 dans la liste (`initialIsOpen`).
À voir si c'est pertinent

https://user-images.githubusercontent.com/45098730/122889228-e64c6280-d342-11eb-8065-f2e651f5b07f.mp4

2021-06-22 10:20 UTC, cedric-famibelle-pronzola approved these changes

2021-06-22 10:26 UTC, merged