[WIP] Ajoute la possibilité de certifier ces Bases Adresses Locales
etalab/editeur-bal pull request #372
Opened 2021-07-27 14:08 UTC by GllmR

## ⚠ Attention : cette PR a besoin d'une fonctionnalité provenant de l'API-BAL : la modification par lot (en cours)

Cette PR propose d'ajouter la certification des adresses par la commune.

- Visuellement, on sait quels numéros sont certifiés ou non : 
   
![image](https://user-images.githubusercontent.com/56537238/127167173-68f20c23-c657-4513-88ef-83de8fe33bc1.png)

- Il est également possible de certifier les adresses, à la création ou à la modification : 
   
![image](https://user-images.githubusercontent.com/56537238/127167354-e2cc1815-a6e3-4c7a-9af1-c1c151a904b6.png)

- Un message informatif est affiché si l'utilisateur à déjà publié sa Base Adresse Locale. Ce message permet à l'utilisateur d'obtenir des informations sur la certification. Il lui sera également possible de certifier toutes les adresses de sa Base Adresse Locale automatiquement.
   
![image](https://user-images.githubusercontent.com/56537238/127167866-716c3f08-dfc5-4924-ab09-5bcb85022e5e.png)

2021-07-28 08:17 UTC, tmerlier requested changes

2021-07-28 08:17 UTC, tmerlier commented on components/certification-message.js
> +const CertificationMessage = voies => {
`const CertificationMessage = ({voies}) => {`

2021-07-28 08:17 UTC, tmerlier commented on components/certification-message.js
> +      await Promise.all(voies.voies.map(async voie => {
Nous pourrions économiser ce `Promise.all`, qui peut être assez lourd, en ne l'exécutant que si `!wasInformed` et `wasWelcomed === true`.

2021-07-28 08:17 UTC, tmerlier commented on components/certification-message.js
> +      const allNumeros = []
`certifiedNumeros`

2021-07-28 08:17 UTC, tmerlier commented on components/certification-message.js
> +          intent='success'
Nous devrions afficher ce bouton en gris comme une action "annuler".

2021-07-28 08:35 UTC, cedric-famibelle-pronzola commented on components/grouped-actions.js
> +            </Button>
Pourrait être converti en un composant utilisé par `NumeroEditor` également

2021-07-28 08:43 UTC, GllmR commented on pages/bal/voie.js
> +    const filteredNumeros = numeros?.filter(numero => selectedNumerosIds.includes(numero._id))
`numeros` venant du contexte, il est `null` au chargement de la page. 
Sans ces conditions, la page renvoie une erreur.

2021-08-18 16:25 UTC, tmerlier approved these changes

2021-08-18 16:58 UTC, tmerlier requested changes

2021-08-18 16:58 UTC, tmerlier commented on lib/bal-api/index.js
> +
Doublon de `getCommune`

2021-08-18 16:58 UTC, tmerlier commented on components/map/numero-marker.js
> +          )}
Le code se retrouve dupliqué par l'utilisateur de la ternaire.

2021-09-06 12:04 UTC, tmerlier approved these changes

2021-09-06 12:05 UTC, merged